// Convert a vacinacheck analyze-vaccine response into a FHIR R4
// DocumentReference resource.
//
// Spec we follow (loosely; we do not pretend to be a full FHIR server):
//
//   https://www.hl7.org/fhir/R4/documentreference.html
//
// Why DocumentReference and not Immunization[]: the upstream analyzer
// returns a clinician-style narrative + structured fields. Immunization
// would need a normalised vaccine code per dose (CVX in the US, SBIm in
// Brazil), which we do not currently emit. DocumentReference wraps the
// JSON-and-narrative payload faithfully without lying about coding
// completeness. A later refactor can emit an Immunization Bundle when
// the analyzer can pin every dose to a CVX/SBIm code.
//
// Compliance status:
// - Resource shape validates against the official R4 DocumentReference
//   structure (see tests/test-fhir-shape.mjs).
// - We do NOT claim FHIR conformance certification.
// - The Patient resource is a contained `display`-only stub when the
//   caller does not supply patient identifiers; we never invent ones.

import crypto from "node:crypto";

const LOINC_HISTORY_OF_IMMUNIZATION = {
  system: "http://loinc.org",
  code: "11369-6",
  display: "History of Immunization Narrative",
};

const USCORE_CLINICAL_NOTE_CATEGORY = {
  system: "http://hl7.org/fhir/us/core/CodeSystem/us-core-documentreference-category",
  code: "clinical-note",
  display: "Clinical Note",
};

/**
 * Build a FHIR R4 DocumentReference wrapping a vacinacheck analyze
 * response.
 *
 * @param {object} args
 * @param {object} args.analysis - The JSON returned by the analyze route.
 *   We trust the route to have shape-validated this; we still defend
 *   against missing fields.
 * @param {object} [args.patientInfo] - Optional `{ name, birthDate, sex }`.
 *   We DO NOT emit a Patient resource with identifiers we don't have.
 * @param {string} [args.id] - Stable id; if absent we hash analysis+ts.
 * @param {Date} [args.date] - Override the resource date (used in tests).
 * @returns {object} A DocumentReference R4 resource.
 */
export function buildDocumentReference({ analysis, patientInfo, id, date } = {}) {
  if (!analysis || typeof analysis !== "object") {
    throw new TypeError("buildDocumentReference: analysis must be an object");
  }

  const resourceDate = (date ?? new Date()).toISOString();
  const stableId =
    id ??
    crypto
      .createHash("sha256")
      .update(JSON.stringify(analysis))
      .update(resourceDate)
      .digest("hex")
      .slice(0, 32);

  // Try to assemble a short human-readable narrative summarising the
  // analysis. We never put raw PHI in the description; just counts.
  const description = summariseAnalysis(analysis);

  const attachment = {
    contentType: "application/json",
    data: Buffer.from(JSON.stringify(analysis), "utf-8").toString("base64"),
    title: "VacinaCheck analyze-vaccine output (JSON)",
    creation: resourceDate,
  };

  /** @type {object} */
  const subject =
    patientInfo && (patientInfo.name || patientInfo.birthDate)
      ? { display: patientInfo.name || "Patient (de-identified)" }
      : { display: "Patient (de-identified)" };

  return {
    resourceType: "DocumentReference",
    id: stableId,
    status: "current",
    docStatus: "final",
    type: { coding: [LOINC_HISTORY_OF_IMMUNIZATION], text: LOINC_HISTORY_OF_IMMUNIZATION.display },
    category: [
      {
        coding: [USCORE_CLINICAL_NOTE_CATEGORY],
        text: USCORE_CLINICAL_NOTE_CATEGORY.display,
      },
    ],
    subject,
    date: resourceDate,
    description,
    content: [
      {
        attachment,
        format: {
          system: "urn:oid:1.3.6.1.4.1.19376.1.2.3",
          code: "urn:ihe:iti:xds-sd:text:2008",
          display: "Scanned Document (JSON)",
        },
      },
    ],
    context: {
      // We don't have an Encounter or Period to point at; we leave this
      // empty rather than fabricate one.
      sourcePatientInfo:
        patientInfo && (patientInfo.name || patientInfo.birthDate)
          ? {
              display: [
                patientInfo.name,
                patientInfo.birthDate ? `DOB ${patientInfo.birthDate}` : null,
                patientInfo.sex ? `Sex ${patientInfo.sex}` : null,
              ]
                .filter(Boolean)
                .join(", "),
            }
          : undefined,
    },
    meta: {
      profile: ["http://hl7.org/fhir/StructureDefinition/DocumentReference"],
      source: "https://github.com/lucasdcanova/vacinacheck",
      tag: [
        {
          system: "https://lucascanova.com.br/vacinacheck/tag",
          code: "synthetic-mvp",
          display: "Generated by VacinaCheck MVP — not a certified FHIR server",
        },
      ],
    },
  };
}

function summariseAnalysis(a) {
  const done = Array.isArray(a.done_vaccines) ? a.done_vaccines.length : null;
  const missing = Array.isArray(a.missing_for_age) ? a.missing_for_age.length : null;
  const due = Array.isArray(a.due_next) ? a.due_next.length : null;
  const contra = Array.isArray(a.contraindicated_now) ? a.contraindicated_now.length : null;
  const parts = [];
  if (done != null) parts.push(`${done} vaccines done`);
  if (missing != null) parts.push(`${missing} missing for age`);
  if (due != null) parts.push(`${due} due next`);
  if (contra != null) parts.push(`${contra} contraindicated now`);
  return parts.length > 0
    ? "VacinaCheck reconciliation summary: " + parts.join(", ")
    : "VacinaCheck reconciliation summary.";
}

/**
 * Shape-validate a DocumentReference. Returns an array of problems;
 * empty array means it passed the minimum we care about.
 */
export function validateDocumentReferenceShape(doc) {
  const problems = [];
  if (!doc || typeof doc !== "object") {
    problems.push("not an object");
    return problems;
  }
  if (doc.resourceType !== "DocumentReference") problems.push("resourceType must be DocumentReference");
  if (typeof doc.id !== "string" || doc.id.length === 0) problems.push("id must be a non-empty string");
  const validStatus = new Set(["current", "superseded", "entered-in-error"]);
  if (!validStatus.has(doc.status)) problems.push(`status must be one of ${[...validStatus].join("/")}`);
  if (!doc.type?.coding?.[0]?.system || !doc.type?.coding?.[0]?.code) {
    problems.push("type.coding[0] must have system + code");
  }
  if (!Array.isArray(doc.content) || doc.content.length === 0) {
    problems.push("content must be non-empty array");
  } else {
    const att = doc.content[0].attachment;
    if (!att || typeof att.contentType !== "string") {
      problems.push("content[0].attachment.contentType must be a string");
    }
    if (!att || typeof att.data !== "string" || att.data.length === 0) {
      problems.push("content[0].attachment.data must be a non-empty base64 string");
    } else {
      // Cheap base64 round-trip check — must decode without throwing
      try {
        Buffer.from(att.data, "base64").toString("utf-8");
      } catch {
        problems.push("content[0].attachment.data is not valid base64");
      }
    }
  }
  return problems;
}
