// Dados compartilhados de vacinas, serviços, exames e produtos
// Usado pela listagem /vacinas e pelas páginas individuais /vacinas/[slug]

export const VACINAS = [
  // ===== VACINAS =====
  {
    id: 'bcg',
    slug: 'bcg',
    nome: 'BCG',
    nomeCompleto: 'Vacina BCG (Bacilo Calmette-Guérin)',
    descricao: 'Previne as formas graves de tuberculose, principalmente miliar e meníngea.',
    descricaoDetalhada: 'A vacina BCG protege contra as formas mais graves da tuberculose, como a meningite tuberculosa e a tuberculose miliar, que são especialmente perigosas em recém-nascidos e crianças pequenas. É uma das vacinas mais antigas e amplamente utilizadas no mundo, sendo parte do calendário nacional de vacinação do Brasil.',
    indicacao: 'Ao nascer',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: 'Dose única ao nascer, preferencialmente nas primeiras 12 horas de vida. Pode ser aplicada até os 4 anos de idade.',
    contraindicacoes: [
      'Recém-nascidos com peso inferior a 2 kg',
      'Crianças com imunodeficiências congênitas ou adquiridas',
      'Crianças filhas de mães que usaram imunossupressores na gestação',
      'Portadores de HIV com imunossupressão grave',
    ],
    efeitosColaterais: [
      'Nódulo local que evolui para pústula e crosta',
      'Cicatriz característica no local da aplicação',
      'Eventualmente, gânglios axilares aumentados',
    ],
    cuidados: 'Não cobrir o local da aplicação. A evolução da lesão vacinal (nódulo, pústula, crosta e cicatriz) é normal e leva de 6 a 12 semanas. Não aplicar produtos no local.',
    faq: [
      {
        pergunta: 'A cicatriz da BCG é normal?',
        resposta: 'Sim, a cicatriz é esperada e indica que a vacina funcionou. Ela se forma ao longo de 3 a 6 meses após a aplicação.',
      },
      {
        pergunta: 'E se não formar cicatriz?',
        resposta: 'A ausência de cicatriz não significa que a vacina não funcionou. Estudos mostram que a proteção ocorre mesmo sem a formação da marca. Não é recomendada a revacinação.',
      },
    ],
    keywords: ['vacina bcg florianópolis', 'bcg recém-nascido', 'vacina tuberculose bebê', 'bcg ao nascer'],
  },
  {
    id: 'hepatite-b',
    slug: 'hepatite-b',
    nome: 'Hepatite B',
    nomeCompleto: 'Vacina Hepatite B Recombinante',
    descricao: 'Previne a infecção pelo vírus da hepatite B.',
    descricaoDetalhada: 'A vacina contra hepatite B protege contra a infecção pelo vírus HBV, que pode causar doença hepática crônica, cirrose e câncer de fígado. É uma das primeiras vacinas aplicadas ao recém-nascido, idealmente nas primeiras 12 horas de vida, para prevenir a transmissão vertical (da mãe para o bebê).',
    indicacao: 'Ao nascer, 2, 4 e 6 meses',
    categoria: 'Todos',
    tipo: 'vacina',
    esquemaVacinal: 'Primeira dose ao nascer (até 12h de vida). As doses seguintes aos 2, 4 e 6 meses são aplicadas como parte da vacina pentavalente ou hexavalente. Adultos não vacinados: 3 doses (0, 1 e 6 meses).',
    contraindicacoes: [
      'Reação anafilática prévia a algum componente da vacina',
      'Púrpura trombocitopênica pós-vacinação anterior',
    ],
    efeitosColaterais: [
      'Dor e vermelhidão no local da aplicação',
      'Febre baixa (rara)',
      'Mal-estar e fadiga leves',
    ],
    cuidados: 'Pode ser aplicada junto com outras vacinas do calendário. Profissionais de saúde devem verificar soroconversão após o esquema completo.',
    faq: [
      {
        pergunta: 'Adultos precisam tomar a vacina de hepatite B?',
        resposta: 'Sim, adultos não vacinados ou com esquema incompleto devem completar as 3 doses. Profissionais de saúde, manicures e tatuadores têm indicação especial.',
      },
      {
        pergunta: 'A vacina de hepatite B é segura para gestantes?',
        resposta: 'Sim. A vacina é segura e recomendada para gestantes que não foram vacinadas anteriormente.',
      },
    ],
    keywords: ['vacina hepatite b florianópolis', 'hepatite b recém-nascido', 'vacina hepatite b adulto'],
  },
  {
    id: 'penta',
    slug: 'pentavalente',
    nome: 'Pentavalente',
    nomeCompleto: 'Vacina Pentavalente (DTPa-HB-Hib)',
    descricao: 'Protege contra difteria, tétano, coqueluche, hepatite B e Haemophilus influenzae tipo b.',
    descricaoDetalhada: 'A vacina pentavalente oferece proteção contra cinco doenças em uma única aplicação: difteria, tétano, coqueluche (pertussis), hepatite B e infecções por Haemophilus influenzae tipo b (que causa meningite e pneumonia). A versão da rede privada (DTPa) utiliza pertussis acelular, que causa menos efeitos colaterais que a versão de célula inteira do SUS.',
    indicacao: '2, 4 e 6 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: '3 doses aos 2, 4 e 6 meses de idade. Reforços com DTPa aos 15 meses e 4 anos.',
    contraindicacoes: [
      'Reação anafilática a dose anterior ou componente da vacina',
      'Encefalopatia nos 7 dias após dose anterior de vacina com componente pertussis',
    ],
    efeitosColaterais: [
      'Dor, vermelhidão e inchaço no local',
      'Febre',
      'Irritabilidade e choro',
      'Sonolência',
    ],
    cuidados: 'Manter calendário em dia. A versão acelular (DTPa) da rede privada causa menos reações que a versão de célula inteira (DTPw) do SUS.',
    faq: [
      {
        pergunta: 'Qual a diferença entre a pentavalente do SUS e da rede privada?',
        resposta: 'A principal diferença é o componente pertussis: a rede privada usa a versão acelular (DTPa), que causa menos febre e reações locais. A proteção é equivalente.',
      },
    ],
    keywords: ['vacina pentavalente florianópolis', 'pentavalente bebê', 'vacina 5 em 1'],
  },
  {
    id: 'hexa',
    slug: 'hexavalente',
    nome: 'Hexavalente',
    nomeCompleto: 'Vacina Hexavalente (DTPa-HB-IPV-Hib)',
    descricao: 'Protege contra difteria, tétano, coqueluche, hepatite B, poliomielite e Haemophilus influenzae tipo b.',
    descricaoDetalhada: 'A vacina hexavalente é a mais completa disponível para bebês, protegendo contra seis doenças em uma única aplicação: difteria, tétano, coqueluche, hepatite B, poliomielite e Haemophilus influenzae tipo b. Disponível apenas na rede privada, reduz o número de injeções e utiliza o componente pertussis acelular, com menos efeitos colaterais.',
    indicacao: '2 e 6 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: 'Aplicada aos 2 e 6 meses de idade, substituindo a pentavalente e a VIP nessas doses. Aos 4 meses, aplica-se a pentavalente.',
    contraindicacoes: [
      'Reação anafilática a dose anterior ou componente da vacina',
      'Encefalopatia nos 7 dias após dose anterior de vacina com componente pertussis',
    ],
    efeitosColaterais: [
      'Dor e inchaço no local da aplicação',
      'Febre moderada',
      'Irritabilidade',
      'Perda de apetite temporária',
    ],
    cuidados: 'Exclusiva da rede privada. Pode ser combinada com outras vacinas do calendário no mesmo dia.',
    faq: [
      {
        pergunta: 'A hexavalente substitui quais vacinas?',
        resposta: 'Ela substitui a pentavalente e a vacina de poliomielite injetável (VIP), reduzindo o número de picadas no bebê.',
      },
    ],
    keywords: ['vacina hexavalente florianópolis', 'hexavalente bebê', 'vacina 6 em 1'],
  },
  {
    id: 'vip',
    slug: 'poliomielite',
    nome: 'Poliomielite (VIP)',
    nomeCompleto: 'Vacina Inativada contra Poliomielite (VIP)',
    descricao: 'Previne a paralisia infantil (poliomielite).',
    descricaoDetalhada: 'A vacina inativada contra poliomielite (VIP) protege contra os três tipos de poliovírus que causam a paralisia infantil. A VIP é a versão injetável, mais segura que a oral (VOP), pois não utiliza vírus vivo e elimina o risco, embora extremamente raro, de paralisia associada à vacina.',
    indicacao: '2, 4 e 6 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: '3 doses aos 2, 4 e 6 meses. Reforços aos 15 meses e 4 anos. Na rede privada, todas as doses são com VIP (injetável).',
    contraindicacoes: [
      'Reação anafilática a dose anterior',
      'Alergia a estreptomicina, neomicina ou polimixina B',
    ],
    efeitosColaterais: [
      'Dor e vermelhidão no local',
      'Febre baixa (incomum)',
    ],
    cuidados: 'Na rede privada, recomenda-se usar apenas VIP (injetável) em todas as doses, evitando a VOP (gotinha).',
    faq: [
      {
        pergunta: 'Qual a diferença entre a gotinha e a injetável?',
        resposta: 'A VOP (gotinha) usa vírus vivo atenuado e a VIP (injetável) usa vírus inativado. A VIP é mais segura e igualmente eficaz. Na rede privada, usa-se apenas VIP.',
      },
    ],
    keywords: ['vacina poliomielite florianópolis', 'vacina paralisia infantil', 'vip vacina bebê'],
  },
  {
    id: 'pneumo-10',
    slug: 'pneumococica-10',
    nome: 'Pneumocócica 10',
    nomeCompleto: 'Vacina Pneumocócica 10-valente Conjugada',
    descricao: 'Previne doenças invasivas e otite média aguda causadas por Streptococcus pneumoniae.',
    descricaoDetalhada: 'A vacina pneumocócica 10-valente protege contra 10 sorotipos de Streptococcus pneumoniae, bactéria responsável por pneumonia, meningite, otite média e sepse. É a versão disponível no SUS. Na rede privada, estão disponíveis versões com proteção mais ampla (13, 15 ou 20 sorotipos).',
    indicacao: '2, 4 e 12 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: '2 doses aos 2 e 4 meses, com reforço aos 12 meses. Disponível no SUS.',
    contraindicacoes: [
      'Reação anafilática a dose anterior ou componente da vacina',
    ],
    efeitosColaterais: [
      'Dor e vermelhidão no local',
      'Febre',
      'Irritabilidade',
    ],
    cuidados: 'Na rede privada, considere as versões 13 ou 15-valente para proteção mais ampla.',
    faq: [
      {
        pergunta: 'Qual a diferença entre pneumo 10, 13, 15 e 20?',
        resposta: 'O número indica quantos sorotipos de pneumococos a vacina cobre. Quanto maior, mais ampla a proteção. A pneumo 10 está no SUS; as 13, 15 e 20 são exclusivas da rede privada.',
      },
    ],
    keywords: ['vacina pneumocócica florianópolis', 'pneumo 10 bebê', 'vacina pneumonia bebê'],
  },
  {
    id: 'pneumo-13',
    slug: 'pneumococica-13',
    nome: 'Pneumocócica 13',
    nomeCompleto: 'Vacina Pneumocócica 13-valente Conjugada',
    descricao: 'Proteção ampliada contra 13 sorotipos de pneumococos.',
    descricaoDetalhada: 'A vacina pneumocócica 13-valente oferece proteção contra 13 sorotipos de Streptococcus pneumoniae, sendo mais abrangente que a versão 10-valente do SUS. Protege contra pneumonia, meningite, otite média e infecções generalizadas causadas por pneumococos.',
    indicacao: 'A partir de 2 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: 'Bebês: 3 doses aos 2, 4 e 6 meses com reforço entre 12 e 15 meses. Crianças e adultos não vacinados: esquema conforme idade.',
    contraindicacoes: [
      'Reação anafilática a dose anterior ou ao toxoide diftérico',
    ],
    efeitosColaterais: [
      'Dor e inchaço no local',
      'Febre',
      'Irritabilidade e sonolência',
    ],
    cuidados: 'Exclusiva da rede privada. Pode ser intercambiada com a pneumo 10 do SUS sob orientação médica.',
    faq: [
      {
        pergunta: 'Meu filho tomou a pneumo 10 no SUS. Posso complementar com a 13?',
        resposta: 'Sim, é possível fazer doses adicionais com a pneumo 13 para ampliar a proteção. Consulte o profissional de saúde para o esquema adequado.',
      },
    ],
    keywords: ['vacina pneumocócica 13 florianópolis', 'pneumo 13 preço', 'pneumocócica conjugada'],
  },
  {
    id: 'pneumo-15',
    slug: 'pneumococica-15',
    nome: 'Pneumocócica 15',
    nomeCompleto: 'Vacina Pneumocócica 15-valente Conjugada',
    descricao: 'Proteção ampliada contra 15 sorotipos de pneumococos.',
    descricaoDetalhada: 'A vacina pneumocócica 15-valente é uma das mais recentes disponíveis, oferecendo proteção contra 15 sorotipos de Streptococcus pneumoniae. Inclui sorotipos adicionais responsáveis por casos graves de doença pneumocócica invasiva.',
    indicacao: 'A partir de 2 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: 'Bebês: esquema de 3 doses com reforço conforme orientação médica. Adultos: dose única ou esquema sequencial com pneumo 20.',
    contraindicacoes: [
      'Hipersensibilidade a componentes da vacina',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Febre',
      'Fadiga',
    ],
    cuidados: 'Exclusiva da rede privada. Consulte o médico para o melhor esquema vacinal.',
    faq: [
      {
        pergunta: 'A pneumo 15 é melhor que a 13?',
        resposta: 'Ela cobre 2 sorotipos adicionais. A escolha depende da disponibilidade e orientação médica. Ambas oferecem boa proteção.',
      },
    ],
    keywords: ['vacina pneumocócica 15 florianópolis', 'pneumo 15 bebê'],
  },
  {
    id: 'pneumo-20',
    slug: 'pneumococica-20',
    nome: 'Pneumocócica 20',
    nomeCompleto: 'Vacina Pneumocócica 20-valente Conjugada',
    descricao: 'Proteção mais ampla disponível contra pneumococos.',
    descricaoDetalhada: 'A vacina pneumocócica 20-valente é a mais abrangente disponível, protegendo contra 20 sorotipos de Streptococcus pneumoniae. Especialmente recomendada para adultos e idosos, que têm maior risco de doença pneumocócica invasiva grave.',
    indicacao: 'Adultos',
    categoria: 'Adultos',
    tipo: 'vacina',
    esquemaVacinal: 'Adultos a partir de 18 anos: dose única. Para idosos e grupos de risco, pode ser usada em esquema sequencial.',
    contraindicacoes: [
      'Hipersensibilidade a componentes da vacina',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Fadiga',
      'Dor de cabeça',
      'Dor muscular',
    ],
    cuidados: 'Recomendada especialmente para maiores de 60 anos, portadores de doenças crônicas e imunossuprimidos.',
    faq: [
      {
        pergunta: 'Idosos devem tomar a pneumo 20?',
        resposta: 'Sim, a SBIm recomenda a vacinação pneumocócica para todos os adultos a partir de 60 anos. A pneumo 20 é a opção com proteção mais ampla disponível.',
      },
    ],
    keywords: ['vacina pneumocócica 20 florianópolis', 'pneumo 20 adulto', 'vacina pneumonia idoso'],
  },
  {
    id: 'rotavirus',
    slug: 'rotavirus',
    nome: 'Rotavírus',
    nomeCompleto: 'Vacina Rotavírus Humano (pentavalente)',
    descricao: 'Previne diarreia grave causada por rotavírus.',
    descricaoDetalhada: 'A vacina contra rotavírus protege contra a principal causa de diarreia grave em crianças pequenas. O rotavírus é altamente contagioso e pode causar desidratação severa, hospitalização e, em casos extremos, óbito. A versão da rede privada é pentavalente (5 sorotipos), enquanto a do SUS é monovalente.',
    indicacao: '2 e 4 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: 'Rede privada (pentavalente): 3 doses aos 2, 4 e 6 meses. SUS (monovalente): 2 doses aos 2 e 4 meses. Primeira dose até 3 meses e 15 dias; última dose até 7 meses e 29 dias.',
    contraindicacoes: [
      'Idade acima do limite (7 meses e 29 dias)',
      'Imunodeficiência grave',
      'História de intussuscepção intestinal',
      'Malformação congênita do trato gastrointestinal',
    ],
    efeitosColaterais: [
      'Diarreia leve',
      'Vômitos',
      'Irritabilidade',
      'Febre baixa',
    ],
    cuidados: 'Vacina oral (em gotas). Tem prazos rigorosos de idade para aplicação que não podem ser ultrapassados. Agendar o quanto antes.',
    faq: [
      {
        pergunta: 'Meu bebê passou da idade. Pode tomar a vacina de rotavírus?',
        resposta: 'Infelizmente não. A vacina de rotavírus tem limite rígido de idade: primeira dose até 3 meses e 15 dias, e esquema completo até 7 meses e 29 dias. Após esses prazos, não pode ser aplicada.',
      },
    ],
    keywords: ['vacina rotavírus florianópolis', 'rotavirus bebê', 'vacina diarreia bebê'],
  },
  {
    id: 'meningo-c',
    slug: 'meningococica-c',
    nome: 'Meningocócica C',
    nomeCompleto: 'Vacina Meningocócica C Conjugada',
    descricao: 'Previne doença meningocócica causada pelo sorogrupo C.',
    descricaoDetalhada: 'A vacina meningocócica C protege contra a meningite e infecções generalizadas (meningococcemia) causadas pela bactéria Neisseria meningitidis do sorogrupo C. A doença meningocócica é grave, de evolução rápida, com alta letalidade e risco de sequelas.',
    indicacao: '3, 5 e 12 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: '2 doses aos 3 e 5 meses com reforço aos 12 meses. Disponível no SUS. Na rede privada, recomenda-se substituir pela meningocócica ACWY para proteção mais ampla.',
    contraindicacoes: [
      'Reação anafilática a dose anterior',
      'Hipersensibilidade a componentes da vacina',
    ],
    efeitosColaterais: [
      'Dor e vermelhidão no local',
      'Febre',
      'Irritabilidade',
    ],
    cuidados: 'Na rede privada, considere a vacina meningocócica ACWY, que oferece proteção mais ampla (4 sorogrupos).',
    faq: [
      {
        pergunta: 'É melhor tomar a meningo C ou a ACWY?',
        resposta: 'A ACWY protege contra 4 sorogrupos (A, C, W e Y), sendo mais completa. Na rede privada, recomenda-se a ACWY. A meningo C está disponível gratuitamente no SUS.',
      },
    ],
    keywords: ['vacina meningite c florianópolis', 'meningocócica c bebê', 'vacina meningite'],
  },
  {
    id: 'meningo-acwy',
    slug: 'meningococica-acwy',
    nome: 'Meningocócica ACWY',
    nomeCompleto: 'Vacina Meningocócica ACWY Conjugada',
    descricao: 'Previne meningite e infecções generalizadas causadas pelos meningococos A, C, W e Y.',
    descricaoDetalhada: 'A vacina meningocócica ACWY protege contra quatro sorogrupos da bactéria Neisseria meningitidis (A, C, W e Y), responsáveis por meningite bacteriana e meningococcemia. A doença meningocócica pode evoluir rapidamente para quadros graves, com taxa de letalidade de até 20% e sequelas em até 20% dos sobreviventes.',
    indicacao: '3, 5, 12 meses e adolescentes',
    categoria: 'Todos',
    tipo: 'vacina',
    esquemaVacinal: 'Bebês: 2 doses aos 3 e 5 meses, com reforço aos 12 meses. Reforço aos 5 anos e na adolescência (11-12 anos). Adolescentes não vacinados: 2 doses.',
    contraindicacoes: [
      'Reação anafilática a dose anterior',
      'Hipersensibilidade a componentes da vacina, incluindo toxoide diftérico ou tetânico',
    ],
    efeitosColaterais: [
      'Dor e vermelhidão no local',
      'Febre',
      'Dor de cabeça',
      'Fadiga',
      'Irritabilidade (em bebês)',
    ],
    cuidados: 'Recomendada pela SBIm para todas as crianças e adolescentes. Exclusiva da rede privada.',
    faq: [
      {
        pergunta: 'Adolescentes precisam de reforço da meningocócica?',
        resposta: 'Sim, a SBIm recomenda um reforço com ACWY na adolescência (11-12 anos) ou dose única para adolescentes nunca vacinados. É importante pelo risco aumentado nessa faixa etária.',
      },
    ],
    keywords: ['vacina meningite acwy florianópolis', 'meningocócica acwy preço', 'vacina meningite adolescente'],
  },
  {
    id: 'meningo-b',
    slug: 'meningococica-b',
    nome: 'Meningocócica B',
    nomeCompleto: 'Vacina Meningocócica B Recombinante',
    descricao: 'Previne meningite e infecções generalizadas causadas pelo meningococo B.',
    descricaoDetalhada: 'A vacina meningocócica B protege contra o sorogrupo B da Neisseria meningitidis, um dos principais causadores de meningite bacteriana no Brasil. Disponível exclusivamente na rede privada, é especialmente importante para bebês e crianças pequenas, que são os mais vulneráveis.',
    indicacao: '3, 5 e 12 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: 'Bebês: 2 doses aos 3 e 5 meses, com reforço aos 12 meses. Crianças maiores e adolescentes: 2 doses com intervalo de 1 a 2 meses.',
    contraindicacoes: [
      'Reação anafilática a dose anterior ou componente da vacina',
    ],
    efeitosColaterais: [
      'Febre (mais frequente que outras vacinas)',
      'Dor e vermelhidão intensas no local',
      'Irritabilidade',
      'Pode-se usar antitérmico profilático quando aplicada com outras vacinas',
    ],
    cuidados: 'Tende a causar mais febre que outras vacinas. Quando aplicada junto com outras vacinas, o médico pode recomendar uso profilático de antitérmico.',
    faq: [
      {
        pergunta: 'A vacina meningo B causa muita febre?',
        resposta: 'A febre é um efeito colateral mais frequente nesta vacina, especialmente quando aplicada junto com outras. É possível usar antitérmico profilático sob orientação médica para minimizar o desconforto.',
      },
    ],
    keywords: ['vacina meningite b florianópolis', 'meningocócica b preço', 'vacina meningite b bebê'],
  },
  {
    id: 'febre-amarela',
    slug: 'febre-amarela',
    nome: 'Febre Amarela',
    nomeCompleto: 'Vacina Febre Amarela (Atenuada)',
    descricao: 'Previne a febre amarela.',
    descricaoDetalhada: 'A vacina contra febre amarela protege contra a doença viral transmitida por mosquitos, que pode causar icterícia, hemorragias e insuficiência hepática. O Brasil é área endêmica, e a vacinação é essencial. Também é exigida para viajantes internacionais que visitam ou saem de áreas de risco.',
    indicacao: '9 meses e 4 anos',
    categoria: 'Todos',
    tipo: 'vacina',
    esquemaVacinal: 'Primeira dose aos 9 meses e reforço aos 4 anos. A partir de 2017, a OMS reconhece que uma dose é suficiente para proteção ao longo da vida, mas o Brasil mantém o esquema de 2 doses.',
    contraindicacoes: [
      'Crianças menores de 6 meses',
      'Gestantes (exceto em situações de alto risco)',
      'Imunossuprimidos graves',
      'Alergia grave a ovo de galinha',
      'Pessoas com doenças do timo',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Febre e mal-estar (5 a 7 dias após)',
      'Dor de cabeça',
      'Dor muscular',
    ],
    cuidados: 'Não aplicar junto com a tríplice viral em menores de 2 anos (intervalo de 30 dias). Emitimos o Certificado Internacional de Vacinação (CIVP) quando necessário.',
    faq: [
      {
        pergunta: 'Preciso da vacina de febre amarela para viajar?',
        resposta: 'Depende do destino. Diversos países exigem o Certificado Internacional de Vacinação contra Febre Amarela (CIVP). A vacina deve ser tomada pelo menos 10 dias antes da viagem.',
      },
      {
        pergunta: 'A vacina de febre amarela é dose única?',
        resposta: 'A OMS considera que uma dose garante proteção por toda a vida. No Brasil, o Ministério da Saúde mantém o esquema de duas doses (9 meses e 4 anos).',
      },
    ],
    keywords: ['vacina febre amarela florianópolis', 'febre amarela viajante', 'certificado vacinação febre amarela'],
  },
  {
    id: 'triplice-viral',
    slug: 'triplice-viral',
    nome: 'Tríplice Viral',
    nomeCompleto: 'Vacina Tríplice Viral (SCR - Sarampo, Caxumba e Rubéola)',
    descricao: 'Previne sarampo, caxumba e rubéola.',
    descricaoDetalhada: 'A vacina tríplice viral protege contra três doenças virais: sarampo, caxumba e rubéola. O sarampo pode causar pneumonia e encefalite; a caxumba pode levar a meningite e orquite; e a rubéola na gestação pode causar síndrome da rubéola congênita com malformações fetais graves.',
    indicacao: '12 meses',
    categoria: 'Todos',
    tipo: 'vacina',
    esquemaVacinal: 'Primeira dose aos 12 meses e segunda dose aos 15 meses (com tetraviral ou tríplice viral + varicela separadas). Adultos nascidos após 1960 que não comprovem 2 doses devem completar o esquema.',
    contraindicacoes: [
      'Gestantes',
      'Imunossuprimidos graves',
      'Alergia grave a neomicina ou gelatina',
      'Uso recente de imunoglobulinas ou sangue (aguardar intervalo)',
    ],
    efeitosColaterais: [
      'Febre (5 a 12 dias após)',
      'Exantema (manchas na pele)',
      'Dor articular (mais comum em adultos)',
      'Inchaço de glândulas salivares',
    ],
    cuidados: 'Mulheres em idade fértil devem evitar gravidez por 30 dias após a vacinação. Intervalo de 30 dias com vacina de febre amarela em menores de 2 anos.',
    faq: [
      {
        pergunta: 'Adultos precisam tomar tríplice viral?',
        resposta: 'Sim, adultos nascidos após 1960 que não comprovem duas doses devem ser vacinados. Especialmente importante para profissionais de saúde e viajantes.',
      },
    ],
    keywords: ['vacina tríplice viral florianópolis', 'vacina sarampo florianópolis', 'vacina caxumba rubéola'],
  },
  {
    id: 'tetraviral',
    slug: 'tetraviral',
    nome: 'Tetraviral',
    nomeCompleto: 'Vacina Tetraviral (SCRV - Sarampo, Caxumba, Rubéola e Varicela)',
    descricao: 'Previne sarampo, caxumba, rubéola e varicela.',
    descricaoDetalhada: 'A vacina tetraviral combina a proteção da tríplice viral (sarampo, caxumba e rubéola) com a proteção contra varicela (catapora) em uma única aplicação, reduzindo o número de picadas na criança.',
    indicacao: '15 meses',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: 'Dose única aos 15 meses, como segunda dose de tríplice viral e primeira dose de varicela.',
    contraindicacoes: [
      'Gestantes',
      'Imunossuprimidos',
      'Alergia a neomicina ou gelatina',
    ],
    efeitosColaterais: [
      'Febre (pode ser mais intensa que com tríplice viral isolada)',
      'Exantema',
      'Dor no local',
    ],
    cuidados: 'A primeira dose de tríplice viral (12 meses) e tetraviral (15 meses) não devem ser aplicadas simultaneamente para reduzir risco de convulsão febril.',
    faq: [
      {
        pergunta: 'A tetraviral substitui a tríplice viral?',
        resposta: 'Não exatamente. A tetraviral é usada como segunda dose de tríplice viral + primeira dose de varicela aos 15 meses. A primeira dose de tríplice viral é dada isoladamente aos 12 meses.',
      },
    ],
    keywords: ['vacina tetraviral florianópolis', 'vacina sarampo catapora bebê'],
  },
  {
    id: 'varicela',
    slug: 'varicela',
    nome: 'Varicela',
    nomeCompleto: 'Vacina Varicela (Catapora)',
    descricao: 'Previne a varicela (catapora).',
    descricaoDetalhada: 'A vacina contra varicela protege contra a catapora, doença altamente contagiosa causada pelo vírus Varicela-Zóster. Embora geralmente benigna em crianças, pode ser grave em bebês, adultos, gestantes e imunossuprimidos, com risco de pneumonia, encefalite e infecções bacterianas secundárias.',
    indicacao: '15 meses e 4 anos',
    categoria: 'Crianças',
    tipo: 'vacina',
    esquemaVacinal: '2 doses: primeira dose aos 15 meses (pode ser com tetraviral) e segunda dose aos 4 a 6 anos. Crianças maiores e adultos suscetíveis: 2 doses com intervalo de 1 a 3 meses.',
    contraindicacoes: [
      'Gestantes',
      'Imunossuprimidos graves',
      'Alergia grave a neomicina ou gelatina',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Febre baixa',
      'Erupções vesiculares discretas (5 a 26 dias após)',
    ],
    cuidados: 'Mulheres devem evitar gravidez por 30 dias após vacinação. A vacina pode ser aplicada até 5 dias após exposição ao vírus para prevenir ou atenuar a doença.',
    faq: [
      {
        pergunta: 'Quem já teve catapora precisa se vacinar?',
        resposta: 'Em geral, quem teve catapora confirmada tem imunidade. Porém, em caso de dúvida, a vacinação é segura mesmo para quem já teve a doença.',
      },
    ],
    keywords: ['vacina varicela florianópolis', 'vacina catapora florianópolis', 'vacina varicela preço'],
  },
  {
    id: 'hepatite-a',
    slug: 'hepatite-a',
    nome: 'Hepatite A',
    nomeCompleto: 'Vacina Hepatite A Inativada',
    descricao: 'Previne a infecção pelo vírus da hepatite A.',
    descricaoDetalhada: 'A vacina contra hepatite A protege contra a infecção pelo vírus HAV, transmitido por água e alimentos contaminados. A hepatite A pode causar inflamação aguda do fígado, com icterícia, fadiga intensa e, raramente, insuficiência hepática fulminante em adultos.',
    indicacao: '15 meses',
    categoria: 'Crianças',
    tipo: 'vacina',
    esquemaVacinal: '2 doses: primeira aos 12-15 meses e segunda 6 meses após. No SUS, dose única aos 15 meses. Na rede privada, recomenda-se o esquema de 2 doses.',
    contraindicacoes: [
      'Reação anafilática a dose anterior',
      'Hipersensibilidade a componentes da vacina',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Dor de cabeça',
      'Fadiga',
      'Febre baixa (rara)',
    ],
    cuidados: 'Existe a vacina combinada hepatite A+B para adultos que precisam de ambas as proteções.',
    faq: [
      {
        pergunta: 'Adultos devem tomar a vacina de hepatite A?',
        resposta: 'Sim, adultos não vacinados e sem história confirmada da doença devem ser vacinados, especialmente viajantes para áreas endêmicas e manipuladores de alimentos.',
      },
    ],
    keywords: ['vacina hepatite a florianópolis', 'hepatite a crianças', 'vacina hepatite a preço'],
  },
  {
    id: 'dtpa',
    slug: 'dtpa-gestante',
    nome: 'dTpa',
    nomeCompleto: 'Vacina Tríplice Bacteriana Acelular do Adulto (dTpa)',
    descricao: 'Previne difteria, tétano e coqueluche. Essencial para gestantes.',
    descricaoDetalhada: 'A vacina dTpa protege contra difteria, tétano e coqueluche (pertussis), utilizando componente pertussis acelular. É especialmente importante para gestantes, pois os anticorpos produzidos pela mãe são transferidos ao bebê, protegendo-o nos primeiros meses de vida contra a coqueluche, que pode ser fatal em recém-nascidos.',
    indicacao: 'Gestantes a partir de 20 semanas',
    categoria: 'Gestantes',
    tipo: 'vacina',
    esquemaVacinal: 'Gestantes: uma dose a cada gestação, preferencialmente entre a 20a e 36a semana. Adultos: reforço a cada 10 anos. Profissionais de saúde e contactantes de bebês também devem estar em dia.',
    contraindicacoes: [
      'Reação anafilática a dose anterior',
      'Encefalopatia nos 7 dias após dose anterior com componente pertussis',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Dor de cabeça',
      'Fadiga',
      'Febre baixa',
    ],
    cuidados: 'Gestantes devem receber a dTpa a cada gestação, independentemente de vacinação anterior. Familiares e cuidadores do bebê também devem estar vacinados (estratégia "cocoon").',
    faq: [
      {
        pergunta: 'Por que a gestante precisa tomar a dTpa toda gestação?',
        resposta: 'Porque os anticorpos contra coqueluche diminuem com o tempo. Cada gestação requer uma nova dose para garantir a transferência de anticorpos protetores ao bebê, que está vulnerável nos primeiros meses de vida.',
      },
      {
        pergunta: 'O pai e avós também devem tomar?',
        resposta: 'Sim, a estratégia "cocoon" recomenda que todos que terão contato próximo com o recém-nascido estejam vacinados contra coqueluche.',
      },
    ],
    keywords: ['vacina dTpa gestante florianópolis', 'vacina coqueluche gestante', 'dTpa gravidez'],
  },
  {
    id: 'dtpa-ipv',
    slug: 'dtpa-poliomielite',
    nome: 'dTpa + IPV',
    nomeCompleto: 'Vacina Tríplice Bacteriana Acelular com Poliomielite (dTpa-IPV)',
    descricao: 'Previne difteria, tétano, coqueluche e poliomielite.',
    descricaoDetalhada: 'A vacina dTpa-IPV combina proteção contra difteria, tétano e coqueluche com poliomielite em uma única aplicação. Utilizada como reforço para crianças e adultos, reduz o número de injeções necessárias.',
    indicacao: 'Reforço',
    categoria: 'Crianças',
    tipo: 'vacina',
    esquemaVacinal: 'Reforço aos 4-5 anos (quando necessário atualizar tanto dTpa quanto poliomielite). Também indicada para viajantes que precisam de reforço de poliomielite.',
    contraindicacoes: [
      'Reação anafilática a dose anterior',
      'Encefalopatia pós-vacinal',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Febre',
      'Fadiga',
    ],
    cuidados: 'Substitui a necessidade de aplicar dTpa e VIP separadamente.',
    faq: [
      {
        pergunta: 'Quando usar dTpa-IPV ao invés de dTpa?',
        resposta: 'Quando é necessário reforço de poliomielite junto com difteria, tétano e coqueluche. Comum no reforço dos 4-5 anos e para viajantes.',
      },
    ],
    keywords: ['vacina dTpa IPV florianópolis', 'reforço poliomielite criança'],
  },
  {
    id: 'influenza',
    slug: 'gripe',
    nome: 'Influenza (Gripe) Tetravalente',
    nomeCompleto: 'Vacina Influenza Tetravalente (Inativada)',
    descricao: 'Previne a gripe e suas complicações. Cepas atualizadas.',
    descricaoDetalhada: 'A vacina tetravalente contra gripe protege contra quatro cepas do vírus Influenza (2 tipos A e 2 tipos B), atualizadas anualmente conforme recomendação da OMS. A gripe pode causar complicações graves como pneumonia, especialmente em idosos, crianças, gestantes e portadores de doenças crônicas.',
    indicacao: 'Anual',
    categoria: 'Todos',
    tipo: 'vacina',
    esquemaVacinal: 'Dose anual para todas as idades a partir de 6 meses. Crianças de 6 meses a 8 anos vacinando pela primeira vez: 2 doses com intervalo de 30 dias.',
    contraindicacoes: [
      'Crianças menores de 6 meses',
      'Reação anafilática a dose anterior ou alergia grave a ovo',
      'Síndrome de Guillain-Barré nas 6 semanas após dose anterior',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Febre baixa',
      'Dor muscular',
      'Dor de cabeça',
    ],
    cuidados: 'A campanha de vacinação contra gripe geralmente ocorre entre março e junho. Vacine-se o quanto antes para proteção durante o outono e inverno.',
    faq: [
      {
        pergunta: 'Preciso tomar a vacina da gripe todo ano?',
        resposta: 'Sim. Os vírus da gripe sofrem mutações constantes, e a composição da vacina é atualizada anualmente. A imunidade também diminui ao longo do ano.',
      },
      {
        pergunta: 'A vacina da gripe pode causar gripe?',
        resposta: 'Não. A vacina é feita com vírus inativados (mortos). Sintomas leves como febre e mal-estar são reações normais do sistema imunológico, não gripe.',
      },
    ],
    keywords: ['vacina gripe florianópolis', 'vacina influenza florianópolis 2026', 'vacina gripe preço', 'vacina gripe tetravalente'],
  },
  {
    id: 'efluelda',
    slug: 'gripe-alta-dose',
    nome: 'Efluelda (Gripe Alta Dose)',
    nomeCompleto: 'Vacina Influenza Tetravalente Alta Dose (Efluelda)',
    descricao: 'Vacina da gripe com alta dose de antígeno, ideal para idosos.',
    descricaoDetalhada: 'A Efluelda é uma vacina contra gripe com quatro vezes mais antígeno que a vacina padrão, desenvolvida especificamente para idosos acima de 60 anos. Com o envelhecimento, o sistema imunológico responde menos à vacinação padrão; a alta dose compensa essa redução, oferecendo proteção significativamente superior.',
    indicacao: '60+ anos',
    categoria: 'Adultos',
    tipo: 'vacina',
    esquemaVacinal: 'Dose única anual para adultos com 60 anos ou mais.',
    contraindicacoes: [
      'Reação anafilática a dose anterior ou alergia grave a ovo',
      'Síndrome de Guillain-Barré nas 6 semanas após dose anterior',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação (pode ser mais intensa que a dose padrão)',
      'Febre',
      'Dor muscular',
      'Fadiga',
    ],
    cuidados: 'Exclusiva para idosos 60+. Estudos mostram superioridade na prevenção de hospitalizações em comparação com a vacina dose padrão.',
    faq: [
      {
        pergunta: 'Qual a diferença entre a gripe normal e a alta dose?',
        resposta: 'A Efluelda tem 4 vezes mais antígeno que a vacina padrão, gerando resposta imunológica mais robusta em idosos. Estudos mostram até 24% mais eficácia na prevenção de gripe confirmada em laboratório.',
      },
    ],
    keywords: ['efluelda florianópolis', 'vacina gripe alta dose idoso', 'vacina gripe idoso florianópolis'],
  },
  {
    id: 'hpv-4',
    slug: 'hpv-quadrivalente',
    nome: 'HPV Quadrivalente',
    nomeCompleto: 'Vacina HPV Quadrivalente (tipos 6, 11, 16 e 18)',
    descricao: 'Previne infecções pelo papilomavírus humano (4 tipos).',
    descricaoDetalhada: 'A vacina HPV quadrivalente protege contra 4 tipos do papilomavírus humano: tipos 16 e 18 (responsáveis por cerca de 70% dos cânceres de colo do útero) e tipos 6 e 11 (responsáveis por 90% das verrugas genitais). Previne câncer de colo do útero, vulva, vagina, ânus, pênis e orofaringe.',
    indicacao: '9 a 45 anos',
    categoria: 'Adolescentes',
    tipo: 'vacina',
    esquemaVacinal: '9 a 14 anos: 2 doses com intervalo de 6 meses. 15 a 45 anos: 3 doses (0, 2 e 6 meses).',
    contraindicacoes: [
      'Reação anafilática a dose anterior',
      'Gestantes (adiar vacinação)',
      'Hipersensibilidade a componentes da vacina',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Inchaço',
      'Vermelhidão',
      'Dor de cabeça',
      'Febre baixa',
    ],
    cuidados: 'O ideal é vacinar antes do início da vida sexual. Porém, mesmo quem já iniciou a vida sexual se beneficia da vacinação.',
    faq: [
      {
        pergunta: 'Meninos também devem tomar a vacina de HPV?',
        resposta: 'Sim. O HPV também causa câncer de pênis, ânus e orofaringe em homens, além de verrugas genitais. A vacinação de meninos também ajuda a reduzir a transmissão.',
      },
      {
        pergunta: 'Quem já tem HPV pode se vacinar?',
        resposta: 'Sim. A vacina protege contra os tipos de HPV aos quais a pessoa ainda não foi exposta. Mesmo quem já teve infecção por um tipo se beneficia da proteção contra os demais.',
      },
    ],
    keywords: ['vacina hpv florianópolis', 'vacina hpv preço', 'vacina hpv homem', 'vacina hpv adolescente'],
  },
  {
    id: 'hpv-9',
    slug: 'hpv-nonavalente',
    nome: 'HPV Nonavalente',
    nomeCompleto: 'Vacina HPV Nonavalente (9 tipos)',
    descricao: 'Proteção ampliada contra 9 tipos de HPV.',
    descricaoDetalhada: 'A vacina HPV nonavalente é a mais completa disponível, protegendo contra 9 tipos de HPV (6, 11, 16, 18, 31, 33, 45, 52 e 58). Cobre aproximadamente 90% dos tipos de HPV causadores de câncer cervical e 90% dos causadores de verrugas genitais.',
    indicacao: '9 a 45 anos',
    categoria: 'Adolescentes',
    tipo: 'vacina',
    esquemaVacinal: '9 a 14 anos: 2 doses com intervalo de 6 meses. 15 a 45 anos: 3 doses (0, 2 e 6 meses).',
    contraindicacoes: [
      'Reação anafilática a dose anterior',
      'Gestantes',
      'Hipersensibilidade a componentes, incluindo leveduras',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Inchaço e vermelhidão',
      'Dor de cabeça',
    ],
    cuidados: 'É a opção mais completa contra HPV. Pode ser usada mesmo em quem já tomou a quadrivalente, para ampliar a proteção.',
    faq: [
      {
        pergunta: 'Qual a diferença entre HPV quadrivalente e nonavalente?',
        resposta: 'A nonavalente protege contra 9 tipos de HPV (vs. 4 da quadrivalente), cobrindo aproximadamente 90% dos cânceres cervicais. A proteção é significativamente mais ampla.',
      },
    ],
    keywords: ['vacina hpv 9 florianópolis', 'hpv nonavalente preço', 'gardasil 9 florianópolis'],
  },
  {
    id: 'herpes-zoster',
    slug: 'herpes-zoster',
    nome: 'Herpes Zóster (Shingrix)',
    nomeCompleto: 'Vacina Herpes Zóster Recombinante (Shingrix)',
    descricao: 'Previne o herpes zóster (cobreiro) e neuralgia pós-herpética.',
    descricaoDetalhada: 'A vacina Shingrix é uma vacina recombinante (não contém vírus vivo) que previne o herpes zóster (cobreiro) e sua complicação mais temida: a neuralgia pós-herpética, uma dor crônica debilitante que pode durar meses ou anos. O herpes zóster é causado pela reativação do vírus Varicela-Zóster, que permanece latente após a catapora.',
    indicacao: '50+ anos',
    categoria: 'Adultos',
    tipo: 'vacina',
    esquemaVacinal: '2 doses com intervalo de 2 meses. Pode ser aplicada em quem já teve herpes zóster e em quem tomou a vacina anterior (Zostavax).',
    contraindicacoes: [
      'Hipersensibilidade a componentes da vacina',
      'Episódio atual de herpes zóster (aguardar resolução)',
    ],
    efeitosColaterais: [
      'Dor intensa no local da aplicação',
      'Dor muscular',
      'Fadiga',
      'Dor de cabeça',
      'Febre e calafrios',
      'Efeitos duram 2-3 dias em média',
    ],
    cuidados: 'Os efeitos colaterais podem ser mais intensos que em outras vacinas, mas são transitórios (2-3 dias). A eficácia é superior a 90% mesmo em idosos.',
    faq: [
      {
        pergunta: 'Quem já teve herpes zóster pode tomar a Shingrix?',
        resposta: 'Sim. A vacina é recomendada mesmo para quem já teve um episódio de herpes zóster, pois a doença pode recorrer. Aguardar a resolução completa do episódio antes de vacinar.',
      },
      {
        pergunta: 'A Shingrix pode ser usada por imunossuprimidos?',
        resposta: 'Sim. Por ser uma vacina recombinante (sem vírus vivo), pode ser usada em imunossuprimidos, que são justamente os que têm maior risco de herpes zóster.',
      },
    ],
    keywords: ['vacina herpes zóster florianópolis', 'shingrix preço', 'vacina cobreiro florianópolis', 'shingrix florianópolis'],
  },
  {
    id: 'dengue',
    slug: 'dengue',
    nome: 'Dengue (Qdenga)',
    nomeCompleto: 'Vacina Dengue Tetravalente (Qdenga)',
    descricao: 'Previne a dengue causada pelos quatro sorotipos do vírus.',
    descricaoDetalhada: 'A vacina Qdenga protege contra os quatro sorotipos do vírus da dengue (DENV-1, 2, 3 e 4). É a vacina de dengue mais moderna disponível no Brasil, aprovada pela Anvisa para pessoas de 4 a 60 anos, independentemente de infecção prévia por dengue. Em Florianópolis, cidade com casos crescentes, a vacinação é uma importante medida de prevenção.',
    indicacao: '4 a 60 anos',
    categoria: 'Todos',
    tipo: 'vacina',
    esquemaVacinal: '2 doses com intervalo de 3 meses.',
    contraindicacoes: [
      'Menores de 4 anos e maiores de 60 anos',
      'Gestantes e lactantes',
      'Imunossuprimidos graves',
      'Hipersensibilidade a componentes da vacina',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Dor de cabeça',
      'Dor muscular',
      'Mal-estar',
      'Febre baixa',
    ],
    cuidados: 'Pode ser aplicada independentemente de ter tido dengue antes. Não interfere com outras vacinas do calendário.',
    faq: [
      {
        pergunta: 'Quem já teve dengue pode tomar a Qdenga?',
        resposta: 'Sim. A Qdenga pode ser aplicada independentemente de história prévia de dengue. Inclusive, estudos mostram que a eficácia é maior em quem já teve dengue.',
      },
      {
        pergunta: 'A vacina protege contra os 4 tipos de dengue?',
        resposta: 'Sim, a Qdenga é tetravalente e protege contra os sorotipos DENV-1, 2, 3 e 4. A proteção pode variar por sorotipo.',
      },
      {
        pergunta: 'A vacina de dengue está disponível no SUS?',
        resposta: 'O SUS tem disponibilidade limitada, priorizando faixas etárias específicas em regiões endêmicas. Na rede privada, está disponível para 4 a 60 anos.',
      },
    ],
    keywords: ['vacina dengue florianópolis', 'qdenga preço florianópolis', 'vacina dengue preço', 'qdenga florianópolis'],
  },
  {
    id: 'febre-tifoide',
    slug: 'febre-tifoide',
    nome: 'Febre Tifoide',
    nomeCompleto: 'Vacina Febre Tifoide Polissacarídica',
    descricao: 'Previne a febre tifoide.',
    descricaoDetalhada: 'A vacina contra febre tifoide protege contra a infecção pela Salmonella typhi, transmitida por água e alimentos contaminados. Especialmente recomendada para viajantes que se dirigem a regiões com saneamento precário na Ásia, África e América Latina.',
    indicacao: 'Viajantes',
    categoria: 'Todos',
    tipo: 'vacina',
    esquemaVacinal: 'Dose única pelo menos 2 semanas antes da viagem. Reforço a cada 3 anos para viajantes frequentes.',
    contraindicacoes: [
      'Crianças menores de 2 anos',
      'Reação anafilática a dose anterior',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Febre baixa',
      'Dor de cabeça',
    ],
    cuidados: 'A vacina não substitui cuidados com higiene e alimentação durante viagens.',
    faq: [
      {
        pergunta: 'Quando tomar a vacina de febre tifoide antes de viajar?',
        resposta: 'Idealmente 2 semanas antes da viagem para garantir proteção adequada. A proteção dura cerca de 3 anos.',
      },
    ],
    keywords: ['vacina febre tifoide florianópolis', 'vacina viajante florianópolis'],
  },
  {
    id: 'vsr-arexvy',
    slug: 'vsr-idosos',
    nome: 'VSR (Arexvy)',
    nomeCompleto: 'Vacina VSR Recombinante para Idosos (Arexvy)',
    descricao: 'Vacina contra Vírus Sincicial Respiratório para idosos.',
    descricaoDetalhada: 'A vacina Arexvy protege idosos contra infecções pelo Vírus Sincicial Respiratório (VSR), que é uma causa importante de pneumonia e bronquite grave em pessoas com mais de 60 anos. O VSR pode levar a hospitalizações e complicações graves nessa faixa etária.',
    indicacao: '60+ anos',
    categoria: 'Adultos',
    tipo: 'vacina',
    esquemaVacinal: 'Dose única para adultos de 60 anos ou mais.',
    contraindicacoes: [
      'Hipersensibilidade a componentes da vacina',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Fadiga',
      'Dor muscular',
      'Dor de cabeça',
    ],
    cuidados: 'Vacina recente no mercado brasileiro. Consulte o médico sobre a indicação.',
    faq: [
      {
        pergunta: 'O que é o VSR?',
        resposta: 'O Vírus Sincicial Respiratório (VSR) é um dos principais causadores de infecções respiratórias graves, especialmente em bebês e idosos. Pode causar bronquiolite em bebês e pneumonia grave em idosos.',
      },
    ],
    keywords: ['vacina vsr idoso florianópolis', 'arexvy florianópolis', 'vacina vsr preço'],
  },
  {
    id: 'vsr-abrysvo',
    slug: 'vsr-gestantes',
    nome: 'VSR (Abrysvo)',
    nomeCompleto: 'Vacina VSR Bivalente para Gestantes (Abrysvo)',
    descricao: 'Vacina contra VSR para gestantes e idosos.',
    descricaoDetalhada: 'A vacina Abrysvo pode ser aplicada em gestantes entre a 32a e 36a semana de gestação para proteger o recém-nascido contra infecções graves pelo VSR nos primeiros meses de vida. Também é indicada para adultos de 60 anos ou mais. A proteção é transferida da mãe para o bebê através da placenta.',
    indicacao: 'Gestantes e 60+',
    categoria: 'Gestantes',
    tipo: 'vacina',
    esquemaVacinal: 'Gestantes: dose única entre 32 e 36 semanas de gestação. Idosos: dose única.',
    contraindicacoes: [
      'Hipersensibilidade a componentes da vacina',
      'Parto prematuro iminente',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Dor de cabeça',
      'Dor muscular',
    ],
    cuidados: 'A vacinação materna é uma alternativa ao Beyfortus (anticorpo monoclonal) para proteção do recém-nascido contra VSR. Não usar ambos simultaneamente.',
    faq: [
      {
        pergunta: 'A vacina VSR na gestação protege o bebê?',
        resposta: 'Sim. Os anticorpos produzidos pela mãe atravessam a placenta e protegem o bebê nos primeiros meses de vida, quando ele é mais vulnerável ao VSR.',
      },
    ],
    keywords: ['vacina vsr gestante florianópolis', 'abrysvo gestante', 'vacina vsr bebê'],
  },
  {
    id: 'beyfortus',
    slug: 'beyfortus',
    nome: 'Beyfortus (Imunização VSR)',
    nomeCompleto: 'Nirsevimabe (Beyfortus) - Imunização Passiva contra VSR',
    descricao: 'Anticorpo monoclonal para prevenção de VSR em bebês.',
    descricaoDetalhada: 'O Beyfortus (nirsevimabe) é um anticorpo monoclonal de longa duração que oferece proteção imediata contra infecções respiratórias causadas pelo VSR em recém-nascidos e lactentes. Diferente de uma vacina, ele fornece anticorpos prontos, não estimulando o sistema imunológico do bebê a produzi-los.',
    indicacao: 'Recém-nascidos',
    categoria: 'Bebês',
    tipo: 'vacina',
    esquemaVacinal: 'Dose única aplicada no recém-nascido, preferencialmente antes da primeira estação de circulação do VSR. Proteção dura cerca de 5 meses.',
    contraindicacoes: [
      'Hipersensibilidade ao nirsevimabe ou componentes',
    ],
    efeitosColaterais: [
      'Reação no local da injeção (vermelhidão, inchaço)',
      'Febre (rara)',
      'Erupção cutânea (rara)',
    ],
    cuidados: 'Não é uma vacina, mas sim uma imunização passiva (anticorpo monoclonal). Oferece proteção imediata, ideal para a primeira estação de VSR do bebê.',
    faq: [
      {
        pergunta: 'Beyfortus é uma vacina?',
        resposta: 'Não. O Beyfortus é um anticorpo monoclonal (imunização passiva). Ele fornece anticorpos prontos para proteger o bebê, enquanto uma vacina estimula o corpo a produzir seus próprios anticorpos.',
      },
    ],
    keywords: ['beyfortus florianópolis', 'nirsevimabe bebê', 'anticorpo vsr recém-nascido'],
  },
  {
    id: 'rhophylac',
    slug: 'rhophylac',
    nome: 'Rhophylac',
    nomeCompleto: 'Imunoglobulina Anti-D (Rhophylac)',
    descricao: 'Imunoglobulina anti-D para gestantes Rh negativo.',
    descricaoDetalhada: 'O Rhophylac é uma imunoglobulina anti-D indicada para gestantes com fator Rh negativo cujo bebê pode ser Rh positivo. Previne a sensibilização materna (doença hemolítica do recém-nascido / eritroblastose fetal), que pode causar anemia grave, icterícia e complicações no bebê.',
    indicacao: 'Gestantes',
    categoria: 'Gestantes',
    tipo: 'vacina',
    esquemaVacinal: 'Dose entre 28 e 34 semanas de gestação e, se necessário, até 72 horas após o parto (se o bebê for Rh positivo). Também indicada após aborto, amniocentese ou sangramento durante a gestação.',
    contraindicacoes: [
      'Gestante Rh positivo',
      'Paciente já sensibilizada (com anticorpos anti-D)',
    ],
    efeitosColaterais: [
      'Dor no local da aplicação',
      'Febre baixa',
      'Mal-estar',
    ],
    cuidados: 'Essencial para gestantes Rh negativo. A falta de administração pode resultar em doença hemolítica grave em gestações futuras.',
    faq: [
      {
        pergunta: 'Toda gestante Rh negativo precisa do Rhophylac?',
        resposta: 'Sim, quando o pai é Rh positivo ou o Rh é desconhecido. A imunoglobulina previne que a mãe produza anticorpos contra o sangue Rh positivo do bebê, protegendo esta e futuras gestações.',
      },
    ],
    keywords: ['rhophylac florianópolis', 'imunoglobulina anti-d gestante', 'rh negativo gestação'],
  },

  // ===== SERVIÇOS =====
  {
    id: 'furo-orelha',
    slug: 'perfuracao-orelha',
    nome: 'Perfuração de Orelha',
    nomeCompleto: 'Perfuração de Orelha com Técnica Humanizada',
    descricao: 'Colocação de brincos com técnica humanizada e estéril.',
    descricaoDetalhada: 'Realizamos perfuração de orelha com técnica estéril e humanizada, utilizando brincos hipoalergênicos em aço cirúrgico. O procedimento é realizado por profissionais de enfermagem capacitados, em ambiente clínico com todos os cuidados de assepsia. Atendemos desde recém-nascidos.',
    indicacao: 'Todas as idades',
    categoria: 'Serviços',
    tipo: 'servico',
    cuidados: 'Higienizar o local conforme orientação, não remover o brinco antes do período recomendado, observar sinais de infecção.',
    faq: [
      {
        pergunta: 'A partir de que idade pode furar a orelha?',
        resposta: 'Pode ser feito desde recém-nascido, preferencialmente após as primeiras vacinas. Recomenda-se que a criança esteja saudável no dia do procedimento.',
      },
      {
        pergunta: 'O procedimento dói?',
        resposta: 'É rápido e causa desconforto momentâneo. Utilizamos técnicas de alívio da dor e distração, especialmente com crianças.',
      },
    ],
    keywords: ['furar orelha florianópolis', 'perfuração orelha bebê florianópolis', 'furar orelha recém-nascido'],
  },
  {
    id: 'aplicacao-brinco',
    slug: 'aplicacao-brinco',
    nome: 'Aplicação de Brinco',
    nomeCompleto: 'Aplicação de Brinco Estéril',
    descricao: 'Procedimento completo de aplicação.',
    descricaoDetalhada: 'Serviço de aplicação de brinco com material estéril e hipoalergênico, realizado por profissionais qualificados em ambiente clínico seguro.',
    indicacao: 'Todas as idades',
    categoria: 'Serviços',
    tipo: 'servico',
    faq: [],
    keywords: ['aplicação brinco florianópolis', 'colocar brinco clínica'],
  },
  {
    id: 'home-care',
    slug: 'vacinacao-domiciliar',
    nome: 'Home Care',
    nomeCompleto: 'Vacinação Domiciliar (Home Care)',
    descricao: 'Atendimento domiciliar para vacinação e procedimentos.',
    descricaoDetalhada: 'Oferecemos serviço de vacinação domiciliar (home care) para quem prefere o conforto de casa. Ideal para idosos com dificuldade de locomoção, famílias com recém-nascidos, empresas e condomínios. Nossa equipe vai até você com toda a estrutura necessária para uma vacinação segura.',
    indicacao: 'Sob agendamento',
    categoria: 'Serviços',
    tipo: 'servico',
    cuidados: 'Agendamento prévio obrigatório. Valor do deslocamento consultado no momento do agendamento.',
    faq: [
      {
        pergunta: 'Como funciona a vacinação em domicílio?',
        resposta: 'Basta agendar pelo WhatsApp informando as vacinas desejadas e o endereço. Nossa equipe vai até você com todo o material necessário, incluindo caixa térmica com controle de temperatura.',
      },
      {
        pergunta: 'Quais vacinas estão disponíveis no home care?',
        resposta: 'Todas as vacinas do nosso catálogo podem ser aplicadas em domicílio, desde que haja agendamento prévio.',
      },
    ],
    keywords: ['vacinação domiciliar florianópolis', 'vacina em casa florianópolis', 'home care vacina'],
  },
  {
    id: 'laserterapia',
    slug: 'laserterapia',
    nome: 'Laserterapia',
    nomeCompleto: 'Laserterapia de Baixa Intensidade',
    descricao: 'Tratamento com laser para feridas e inflamações.',
    descricaoDetalhada: 'A laserterapia de baixa intensidade é utilizada para acelerar a cicatrização de feridas, reduzir inflamações e aliviar dor. Pode ser aplicada no local da vacinação para reduzir dor e hematomas, e em diversas outras condições como aftas, herpes labial e feridas de difícil cicatrização.',
    indicacao: 'Sob avaliação',
    categoria: 'Serviços',
    tipo: 'servico',
    faq: [
      {
        pergunta: 'A laserterapia ajuda na dor da vacina?',
        resposta: 'Sim. A aplicação do laser de baixa intensidade no local da vacinação pode reduzir a dor, o inchaço e acelerar a recuperação.',
      },
    ],
    keywords: ['laserterapia florianópolis', 'laser cicatrização florianópolis'],
  },
  {
    id: 'soroterapia',
    slug: 'soroterapia',
    nome: 'Soroterapia',
    nomeCompleto: 'Soroterapia e Infusão Endovenosa',
    descricao: 'Administração de soro e medicamentos endovenosos.',
    descricaoDetalhada: 'Realizamos administração de soro e medicamentos por via endovenosa em ambiente clínico seguro. A soroterapia é indicada para hidratação, reposição de vitaminas e minerais, e administração de medicamentos prescritos pelo médico.',
    indicacao: 'Sob prescrição',
    categoria: 'Serviços',
    tipo: 'servico',
    cuidados: 'Necessário apresentar prescrição médica. O procedimento é realizado por enfermeiro(a) qualificado(a) em sala equipada.',
    faq: [
      {
        pergunta: 'Preciso de receita para fazer soroterapia?',
        resposta: 'Sim, é obrigatória a apresentação de prescrição médica para qualquer procedimento de soroterapia ou infusão endovenosa.',
      },
    ],
    keywords: ['soroterapia florianópolis', 'soro vitamínico florianópolis', 'infusão endovenosa florianópolis'],
  },

  // ===== INJETÁVEIS =====
  {
    id: 'aplicacao-injetaveis',
    slug: 'aplicacao-injetaveis',
    nome: 'Aplicação de Injetáveis',
    nomeCompleto: 'Aplicação de Medicamentos Injetáveis',
    descricao: 'Aplicação de medicamentos prescritos (IM/SC).',
    descricaoDetalhada: 'Oferecemos serviço de aplicação de medicamentos injetáveis (intramuscular e subcutâneo) prescritos pelo médico. Procedimento realizado por profissionais de enfermagem qualificados com técnica asséptica adequada.',
    indicacao: 'Com receita',
    categoria: 'Injetáveis',
    tipo: 'servico',
    faq: [],
    keywords: ['aplicação injeção florianópolis', 'tomar injeção florianópolis'],
  },
  {
    id: 'aplicacao-vitaminas',
    slug: 'aplicacao-vitaminas',
    nome: 'Aplicação de Vitaminas',
    nomeCompleto: 'Aplicação de Vitaminas Injetáveis',
    descricao: 'Reposição vitamínica injetável.',
    descricaoDetalhada: 'Serviço de aplicação de vitaminas injetáveis prescritas pelo médico, como vitamina B12, vitamina D e complexo B. Procedimento rápido e seguro em ambiente clínico.',
    indicacao: 'Sob prescrição',
    categoria: 'Injetáveis',
    tipo: 'servico',
    faq: [],
    keywords: ['aplicação vitamina b12 florianópolis', 'vitamina injetável florianópolis'],
  },

  // ===== EXAMES =====
  {
    id: 'teste-pezinho',
    slug: 'teste-do-pezinho',
    nome: 'Teste do Pezinho',
    nomeCompleto: 'Teste do Pezinho (Triagem Neonatal)',
    descricao: 'Triagem neonatal para diversas doenças.',
    descricaoDetalhada: 'O teste do pezinho é um exame de triagem neonatal que detecta precocemente diversas doenças metabólicas, genéticas e infecciosas no recém-nascido. Quanto mais cedo diagnosticadas, maiores as chances de tratamento eficaz. Na rede privada, oferecemos versões ampliadas que detectam até centenas de doenças.',
    indicacao: 'Recém-nascidos',
    categoria: 'Exames',
    tipo: 'exame',
    cuidados: 'Realizar entre o 3o e 5o dia de vida. O bebê deve ter se alimentado (leite materno ou fórmula) antes do exame.',
    faq: [
      {
        pergunta: 'Quando fazer o teste do pezinho?',
        resposta: 'O ideal é entre o 3o e o 5o dia de vida do bebê. Pode ser feito até o 30o dia, mas quanto antes, melhor para detecção precoce.',
      },
      {
        pergunta: 'Qual a diferença entre o teste do pezinho básico e ampliado?',
        resposta: 'O básico (SUS) detecta 6 doenças. Os testes ampliados da rede privada podem detectar de 48 a mais de 300 doenças, aumentando significativamente as chances de diagnóstico precoce.',
      },
    ],
    keywords: ['teste do pezinho florianópolis', 'triagem neonatal florianópolis', 'teste pezinho ampliado'],
  },
  {
    id: 'teste-covid',
    slug: 'teste-covid',
    nome: 'Teste Covid-19',
    nomeCompleto: 'Teste Rápido Covid-19 (Antígeno)',
    descricao: 'Teste rápido de antígeno para Covid-19.',
    descricaoDetalhada: 'Realizamos teste rápido de antígeno para detecção do SARS-CoV-2 (Covid-19). O resultado sai em aproximadamente 15 minutos. Indicado para pessoas com sintomas respiratórios ou que tiveram contato com casos confirmados.',
    indicacao: 'Sintomáticos',
    categoria: 'Exames',
    tipo: 'exame',
    faq: [
      {
        pergunta: 'Quando devo fazer o teste de Covid?',
        resposta: 'O teste de antígeno é mais sensível a partir do 2o dia de sintomas. Para contatos assintomáticos, aguardar 5 dias após a exposição.',
      },
    ],
    keywords: ['teste covid florianópolis', 'teste rápido covid centro florianópolis'],
  },
  {
    id: 'perfil-lipidico',
    slug: 'perfil-lipidico',
    nome: 'Perfil Lipídico',
    nomeCompleto: 'Exame de Perfil Lipídico',
    descricao: 'Exame para avaliação de colesterol e triglicerídeos.',
    descricaoDetalhada: 'Exame rápido de sangue capilar para avaliação do perfil lipídico (colesterol total, HDL, LDL e triglicerídeos). Resultado em poucos minutos, sem necessidade de laboratório.',
    indicacao: 'Jejum necessário',
    categoria: 'Exames',
    tipo: 'exame',
    faq: [],
    keywords: ['exame colesterol florianópolis', 'perfil lipídico rápido'],
  },
  {
    id: 'funcao-renal',
    slug: 'funcao-renal',
    nome: 'Função Renal',
    nomeCompleto: 'Exame de Função Renal',
    descricao: 'Avaliação da saúde dos rins.',
    descricaoDetalhada: 'Exame rápido para avaliação da função renal, incluindo creatinina. Resultado em poucos minutos.',
    indicacao: 'Todos',
    categoria: 'Exames',
    tipo: 'exame',
    faq: [],
    keywords: ['exame função renal florianópolis', 'creatinina rápido'],
  },
  {
    id: 'hemoglobina-glicada',
    slug: 'hemoglobina-glicada',
    nome: 'Hemoglobina Glicada',
    nomeCompleto: 'Exame de Hemoglobina Glicada (HbA1c)',
    descricao: 'Controle de diabetes e glicemia.',
    descricaoDetalhada: 'Exame rápido de hemoglobina glicada (HbA1c) para monitoramento do controle glicêmico em pacientes diabéticos ou para rastreamento de diabetes. Reflete a média de glicemia dos últimos 2-3 meses.',
    indicacao: 'Todos',
    categoria: 'Exames',
    tipo: 'exame',
    faq: [],
    keywords: ['hemoglobina glicada florianópolis', 'exame diabetes florianópolis'],
  },
  {
    id: 'beta-hcg',
    slug: 'beta-hcg',
    nome: 'Beta HCG',
    nomeCompleto: 'Exame Beta HCG (Teste de Gravidez)',
    descricao: 'Teste de gravidez sanguíneo.',
    descricaoDetalhada: 'Exame de Beta HCG quantitativo em sangue para confirmação de gravidez. Mais preciso que o teste de farmácia, detecta a gravidez mais precocemente.',
    indicacao: 'Suspeita de gravidez',
    categoria: 'Exames',
    tipo: 'exame',
    faq: [],
    keywords: ['beta hcg florianópolis', 'teste gravidez sangue florianópolis'],
  },
  {
    id: 'exame-dengue',
    slug: 'exame-dengue',
    nome: 'Exame Dengue (NS1 / IgG IgM)',
    nomeCompleto: 'Exame Rápido de Dengue (NS1 / IgG / IgM)',
    descricao: 'Diagnóstico rápido de Dengue.',
    descricaoDetalhada: 'Exame rápido para diagnóstico de dengue, incluindo detecção de antígeno NS1 (fase aguda) e anticorpos IgG/IgM. Resultado em poucos minutos.',
    indicacao: 'Sintomáticos',
    categoria: 'Exames',
    tipo: 'exame',
    faq: [],
    keywords: ['exame dengue florianópolis', 'teste rápido dengue florianópolis'],
  },

  // ===== PRODUTOS =====
  {
    id: 'pikluc',
    slug: 'pikluc',
    nome: 'Pikluc',
    nomeCompleto: 'Pikluc - Alívio da Dor na Vacinação',
    descricao: 'Aparelho para alívio da dor na injeção.',
    descricaoDetalhada: 'O Pikluc é um dispositivo que utiliza vibração e frio para reduzir a dor durante a aplicação de injeções e vacinas. Baseado na teoria do portão da dor, a vibração e o frio competem com o sinal de dor, reduzindo significativamente o desconforto.',
    indicacao: 'Uso local',
    categoria: 'Produtos',
    tipo: 'produto',
    faq: [],
    keywords: ['pikluc florianópolis', 'alívio dor vacina'],
  },
  {
    id: 'buzzy',
    slug: 'fever-friends',
    nome: 'Fever Friends',
    nomeCompleto: 'Fever Friends - Compressas para Febre',
    descricao: 'Compressas adesivas para alívio da febre.',
    descricaoDetalhada: 'Compressas adesivas refrescantes para alívio da febre em crianças. Fáceis de usar, proporcionam conforto imediato durante episódios de febre pós-vacinação.',
    indicacao: 'Uso local',
    categoria: 'Produtos',
    tipo: 'produto',
    faq: [],
    keywords: ['fever friends compressas febre', 'compressa febre criança'],
  },
  {
    id: 'xua',
    slug: 'irrigador-nasal',
    nome: 'Xuá Irrigador Nasal',
    nomeCompleto: 'Xuá - Irrigador Nasal',
    descricao: 'Dispositivo para lavagem nasal.',
    descricaoDetalhada: 'O Xuá é um irrigador nasal prático e eficiente para lavagem nasal com soro fisiológico. Auxilia na prevenção e tratamento de rinite, sinusite e resfriados, além de ajudar na higiene nasal diária.',
    indicacao: 'Uso nasal',
    categoria: 'Produtos',
    tipo: 'produto',
    faq: [],
    keywords: ['irrigador nasal florianópolis', 'lavagem nasal'],
  },
  {
    id: 'brinco',
    slug: 'brinco-esteril',
    nome: 'Brinco Estéril',
    nomeCompleto: 'Brinco Estéril para Perfuração',
    descricao: 'Par de brincos estéreis para perfuração.',
    descricaoDetalhada: 'Brincos estéreis em aço cirúrgico hipoalergênico, especialmente desenvolvidos para perfuração de orelha. Embalagem individual estéril para máxima segurança.',
    indicacao: 'Uso auricular',
    categoria: 'Produtos',
    tipo: 'produto',
    faq: [],
    keywords: ['brinco estéril perfuração', 'brinco hipoalergênico bebê'],
  },
]

// Categorias para filtro na listagem
export const CATEGORIAS = [
  { id: 'Todos', label: 'Todas' },
  { id: 'Bebês', label: 'Bebês e Crianças' },
  { id: 'Adolescentes', label: 'Adolescentes' },
  { id: 'Adultos', label: 'Adultos e Idosos' },
  { id: 'Gestantes', label: 'Gestantes' },
  { id: 'Serviços', label: 'Serviços' },
  { id: 'Injetáveis', label: 'Injetáveis' },
  { id: 'Exames', label: 'Exames' },
  { id: 'Produtos', label: 'Produtos' },
]

// Helpers
export function getVacinaBySlug(slug) {
  return VACINAS.find(v => v.slug === slug)
}

export function getAllSlugs() {
  return VACINAS.map(v => v.slug)
}

export function getVacinasByCategoria(categoria) {
  if (categoria === 'Todos') return VACINAS
  return VACINAS.filter(v => v.categoria === categoria || (categoria === 'Bebês' && v.categoria === 'Crianças'))
}
